server:
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:files
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2

